name: C/C++ CI

on:
  push:
    branches: [ "Grass-Unified" ]
  pull_request:
    branches: [ "Grass-Unified" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: chmod +x setup.sh && bash setup.sh
    - name: make
      run: ./build_kernel.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: build
        path: ./out/Image
              ./out/Image.gz
